name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  var1: value1
jobs:
- job: One
  steps:
  - script: echo First step!

#- job: BuildAndPushDockerImage
#  steps:
#  - task: DockerInstaller@0
#    displayName: 'Install Docker 20.10.7'
#    inputs:
#      dockerVersion: 20.10.7

#  - script: whoami
#    displayName: Say whoami
 
#  - bash: |
#      which bash
#      echo Hello $name
#    displayName: Multiline Bash script
#    env:
#      name: Microsoft

#  - task: Docker@2
#    displayName: buildAndPush
#    inputs:
#      containerRegistry: 'DockerHub Asia'
#      repository: bakirovaasia/tfstest
#      Dockerfile: '**/Dockerfile_from_tomcat'

- job: RunSelenoidAndTesting
  steps:
  - script: docker pull selenoid/chrome:89.0
    displayName: Pulling browser image
  
  - script: docker pull selenoid/video-recorder:latest-release
    displayName: Pulling video-recorder image

  - task: DockerCompose@0
    displayName: 'Down enviroment and run testing'
    inputs:
      dockerComposeCommand: down
      projectName: ies

  - task: DockerCompose@0
    displayName: 'Up enviroment and run testing'
    inputs:
      dockerComposeCommand: up
      dockerComposeFileArgs: 'AGENTDIR=$(Build.Repository.LocalPath)'
      projectName: ies
      arguments: '-d --build'