name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  var1: value1
jobs:
- job: One
  steps:
  - script: echo First step!

- job: BuildAndPushDockerImage
  steps:
  - task: DockerInstaller@0
    displayName: 'Install Docker 20.10.7'
    inputs:
      dockerVersion: 20.10.7

  - script: whoami
    displayName: Say whoami
 
  - bash: |
      which bash
      echo Hello $name
    displayName: Multiline Bash script
    env:
      name: Microsoft

  - task: Docker@2
    displayName: buildAndPush
    inputs:
      containerRegistry: 'DockerHub Asia'
      repository: bakirovaasia/tfstest
      Dockerfile: '**/Dockerfile_from_tomcat'