FROM python:3

WORKDIR /tmp/tests/

COPY ./tests/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./tests/ ./

CMD [ "curl", "http://web:80/", "python", "login_as_adm_test.py" ]