name: $(Date:yyyyMMdd)$(Rev:.r)
pr:
- forPRtest
trigger: none

variables:
  var1: value1

jobs:
- job: One
  pool:
    name: SPK-linux-debug
  steps:
  - checkout: none

  - script: echo test PR trigger! 2 3 4 5 6 7 8 9 10

  - script: |
      if cd ./Selenoid_testing; 
        then git pull; 
        else git clone https://github.com/BakirovaAsia/Selenoid_testing.git ./Selenoid_testing 
      fi
    displayName: Git clone/pull

  - script: |
      cd ./Selenoid_testing
      git fetch origin
      git checkout -b branch-2 origin/branch-2
      git merge forPRtest
      dir 
      echo "run tests!!!!"
    displayName: checkout and run test
#git push origin master 

  - script: |
      git checkout forPRtest
      git merge --no-ff branch-2
      git push origin forPRtest
    displayName: Merge pull request


