name: $(Date:yyyyMMdd)$(Rev:.r)
pr:
  branches:
    include:
    - forPRtest
    exclude:
    - master

variables:
  var1: value1

jobs:
- job: One
  pool:
    name: SPK-linux-debug
    
  steps:
  - script: echo test PR trigger! 2

  - script: whoami && pwd
