name: $(Date:yyyyMMdd)$(Rev:.r)
pr:
- forPRtest
trigger: none

variables:
  var1: value1

jobs:
- job: One
  pool:
    name: SPK-linux-debug
  steps:
  - checkout: none

  - script: echo test PR trigger! 2 3 4 5 6 7 8 9

  - script: |
      if cd ./Selenoid_testing; 
        then git pull origin ; 
        else git clone  https://github.com/BakirovaAsia/Selenoid_testing.git ./Selenoid_testing 
             cd ./Selenoid_testing
             git checkout forPRtest 
             git pull --rebase origin forPRtest;
      fi
    displayName: Git clone/pull

  - script: |
      cd ./Selenoid_testing
      dir
#git push origin master 


