name: $(Date:yyyyMMdd)$(Rev:.r)
pr:
- forPRtest
trigger:
  branches:
    exclude:
    - master
    - forPRtest 
    - branch-2

variables:
  var1: value1

jobs:
- job: One
  pool:
    name: SPK-linux-debug
  steps:
  - checkout: none

  - script: echo test PR trigger! 2 3 4 5 6 7 8

  - script: |
      if cd ./Selenoid_testing; 
        then git pull origin ; 
        else git clone  https://github.com/BakirovaAsia/Selenoid_testing.git ./Selenoid_testing 
             git checkout forPRtest 
             git pull --rebase origin forPRtest;
      fi
    displayName: Git clone/pull

  - script: |
      git config --global user.email "you@mail.com"
      git config --global user.name "YourName"
      git checkout master 
      git pull --rebase origin master
      git merge forPRtest
#git push origin master 

