name: sr_$(Date:yyyyMMdd)$(Rev:.r)
pr: none
trigger: 
- forPRtest

jobs:
- job: SemanticRelease
  pool:
    name: SPK-linux-debug
  steps:
  - checkout: none

  - script: |
      echo  $(Build.SourceBranch)
      echo  $(system.pullRequest.sourceBranch)  

  - script: |

      git clone https://github.com/BakirovaAsia/Selenoid_testing.git .
      
    displayName: Git clone/pull

  - task: NodeTool@0
    displayName: 'Use Node 14.x'
    inputs:
      versionSpec: 14.x
  
  - script: yarn install
    displayName: Install dependencies

  - script: yarn semantic-release
    displayName: Release