name: $(Date:yyyyMMdd)$(Rev:.r)
pr:
- forPRtest
trigger:
  branches:
    exclude:
    - master
    - forPRtest 
    - branch-2

variables:
  var1: value1

jobs:
- job: One
  pool:
    name: SPK-linux-debug
  steps:
  - checkout: none

  - script: echo test PR trigger! 2 3 4 5 6 7 8

  - task: InstallSSHKey@0
    displayName: 'Install an SSH key'
    inputs:
      knownHostsEntry: 'github.com'
      sshPublicKey: '$(ssh-TFS-GitHub)'
      sshKeySecureFile: 'ssh-TFS-GitHub'
    
  - script: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    displayName: Install key
  
  - script: |
      if cd ./Selenoid_testing; 
        then git pull origin ci ; 
        else git clone -b forPRtest  git@github.com:BakirovaAsia/Selenoid_testing.git ./Selenoid_testing;
      fi
    displayName: Git clone/pull
