name: $(Date:yyyyMMdd)$(Rev:.r)
pr:
- master
trigger:
  branches:
    exclude:
    - master
    - forPRtest 

variables:
  var1: value1

jobs:
- job: One
  pool:
    name: SPK-linux-debug
  steps:
  - script: echo test PR trigger! 2 3 4 5

  - script: whoami && pwd
