name: $(Date:yyyyMMdd)$(Rev:.r)
pr:
- forPRtest
trigger: none

variables:
  var1: value1

jobs:
- job: One
  pool:
    name: SPK-linux-debug
  steps:

  - task: DownloadSecureFile@1
    name: PAT_TFS_github_IES
    displayName: 'Download secure file. PAT for vitacoredo'
    inputs:
      secureFile: 'PAT_TFS_github_IES.txt'
  
  - task: InstallSSHKey@0
    displayName: 'Install an SSH key'
    inputs:
      knownHostsEntry: 'github.com'
      sshPublicKey: '$(ssh-BA-GitHub)'
      sshKeySecureFile: 'ssh-BA-GitHub'
    
  - script: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    displayName: Install key

  - script: |
      echo test PR trigger! 24
      echo  $(Build.SourceBranch)
      echo  $(system.pullRequest.sourceBranch)
      cat ./test_pr.yml 

  - script: |
      if cd ./Selenoid_testing; 
        then git pull; 
        else git clone https://github.com/BakirovaAsia/Selenoid_testing.git ./Selenoid_testing 
      fi
    displayName: Git clone/pull

  - script: |
      cd ./Selenoid_testing
      git fetch origin
      git checkout -b forPRtest origin/forPRtest
      git checkout -b branch-2 origin/branch-2
      git merge forPRtest
      cat ./test_pr.yml 
      cat ./images_list
      echo "run tests!!!!"
    displayName: checkout and run test

  - script: |
      cd ./Selenoid_testing
      gh pr merge branch-2 -m
    displayName: PR merge

  - script: |
      cd ./Selenoid_testing
      yarn install
      yarn semantic-release
    env: 
      GH_TOKEN: $(PAT_TFS_github_IES)
    displayName: Release
