name: sr_$(Date:yyyyMMdd)$(Rev:.r)
pr: none
trigger: 
# master
  tags: 
    include:
    - v*

jobs:
- job: SemanticRelease
  pool:
    name: SPK-linux-debug
  steps:
  - checkout: none

  - script: |
      echo  $(Build.SourceBranch)
      echo  $(Build.pullRequest.sourceBranch) 

  - task: InstallSSHKey@0
    displayName: 'Install an SSH key'
    inputs:
      knownHostsEntry: 'github.com'
      sshPublicKey: '$(ssh-BA-GitHub)'
      sshKeySecureFile: 'ssh-BA-GitHub'
    
  - script: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    displayName: Install key

  - script: |
      if cd ./Selenoid_testing; 
        then git pull; 
        else git clone https://github.com/BakirovaAsia/Selenoid_testing.git ./Selenoid_testing 
      fi
    displayName: Git clone/pull

  - task: NodeTool@0
    displayName: 'Use Node 14.x'
    inputs:
      versionSpec: 14.x

  - script: cat ./test_sr.yml

  - script: |
      cd ./Selenoid_testing
      yarn install
      yarn semantic-release
    env: 
      GH_TOKEN: $(PAT_TFS_github_IES)
    displayName: Release
    enabled: false
