name: $(Date:yyyyMMdd)$(Rev:.r)
pr:
- forPRtest
trigger:
  branches:
    exclude:
    - master
    - forPRtest 
    - branch-2

variables:
  var1: value1

jobs:
- job: One
  pool:
    name: SPK-linux-debug
  steps:
  - checkout: none

  - script: echo test PR trigger! 2 3 4 5 6 7 8

  - script: |
      if cd ./Selenoid_testing; 
        then git pull origin ci ; 
        else git clone -b forPRtest  git@github.com:BakirovaAsia/Selenoid_testing.git ./Selenoid_testing;
      fi
    displayName: Git clone/pull
